# Generated by Django 4.2.3 on 2023-07-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luck', '0006_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d/'),
        ),
    ]
