# Generated by Django 4.2.3 on 2023-07-21 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luck', '0009_alter_category_image_alter_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
